### ISSUE TITLE
Verify request timestamp

### ISSUE THREAD

**Issue by ThomasPe** [ThomasPe/Alexa.NET.Security#1]
[This verification step is currently missing:](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service#verifying-that-the-request-was-sent-by-alexa)

> Check the request timestamp to ensure that the request is not an old request being sent as part of a “replay” attack.

**Comment by ThomasPe** [comment]
which does not seem to matter since skills get certified regardless...

**Comment by stoiveyp** [comment]
For completeness I've submitted https://github.com/timheuer/alexa-skills-dotnet/pull/76 to handle the timestamp check required.

**Comment by matteocontrini** [comment]
This issue is actually fixed, right? Thanks!

**Comment by ThomasPe** [comment]
You're right, this package was created back when Alexa.NET had not yet merged this feature. I'll mark this repo as obsolete.
